package h_vectors

import kotlin.random.Random
/*
83) [CHALLENGE] Create a logic that fills an array of 20 positions with random numbers
(between 0 and 99) generated by the computer. Soon after, show the generated numbers
and then sort the array in ascending order, showing in the end the ordered values.
*/

fun main() {
    val array = arrayOfNulls<Int>(100)

    for (position in array.indices) {
        array[position] = Random.nextInt(99)
    }

    println("Array draw: ${array.contentToString()}")

    for (i in array.indices) {
        for (j in array.indices) {
            if (array[i]!! < array[j]!!) {
                val temp = array[i]!!
                array[i] = array[j]
                array[j] = temp
            }
        }
    }

    print("Array in ascending order: ")
    for (i in array.indices) {
        print("${array[i]}, ")
    }
}
