package h_vectors

import kotlin.random.Random
/*
80) Create an algorithm that fills a 30-position array with numbers between 1 and 15
randomly generated by the computer. After that, ask the user to enter a number (key)
and your program should show in which positions this key was found.
Also show how many times the key was generated.
*/

fun main() {
    val array = arrayOfNulls<Int>(30)
    val drawPositions = mutableListOf<Int>()
    var repeatedValue = 0

    for (index in array.indices) {
        array[index] = Random.nextInt(15)
    }

    print("Enter a value: ")
    val value = readln().toInt()

    for (index in array.indices) {
        if (value == array[index]) {
            drawPositions.add(index)
            repeatedValue++
        }
    }

    println("Order of the drawn numbers: ${array.joinToString()}.")

    if (repeatedValue > 1) {
        println("The value was drawn at positions ${drawPositions.joinToString()}.")
        println("The value was drawn $repeatedValue times.")
    } else {
        println("The value was drawn at position ${drawPositions.joinToString()}.")
        println("The value was drawn $repeatedValue time.")
    }
}
