/*
80) Create an algorithm that fills a 30-position array with numbers between 1 and 15
randomly generated by the computer. After that, ask the user to enter a number (key)
and your program should show in which positions this key was found.
Also show how many times the key was generated.
*/
