/*
83) [CHALLENGE] Create a logic that fills an array of 20 positions with random numbers
(between 0 and 99) generated by the computer. Soon after, show the generated numbers
and then sort the array in ascending order, showing in the end the ordered values.
*/
