import a_basic_control_structures.*
import b_basic_conditions.*
import c_compound_conditions.*

fun main() {
    helloWorld()
    welcomeMessage()
    employeeSalary()
    sumBetweenIntegers()
    averageGrade()
    predecessorAndSuccessor()
    displaysDoubleAndThirdPart()
    meterToOtherMeasures()
    moneyConversionRealToDollar()
    paintingWalls()
    returnDelta()
    promotionalPrice()
    increasedSalary()
    carRental()
    employeeSalaryCalculated()
    smokersLifetime()
    speedLimit()
    canIVote()
    studentGrades()
    evenOrOdd()
    leapYear()
    militaryEnlistment()
    womensDay()
    distanceTicket()
    isItPossibleTriangle()
    distanceTicket()
    whichNumberIsGreater()
    studentGPA()
    classifyingLands()
    adjustedSalary()
    typeOfTriangle()
    rockPaperScissorsChallenge()
    drawnNumberChallenge()
    bankLoan()
    bmiScale()
    rentalCar()
    rewardPhysicalActivity()
    adjustingSalary()
}